### ISSUE TITLE
'Inbox' widget for taking notes quickly

### ISSUE THREAD

**Issue by fresheed** [orgzly/orgzly-android#112]
Hello. I'm going to extend Orgzly functionality and would like to know your opinion.
As I use Org for GTD-based planning workflow, there is a need for me to be able to take notes very fast. I think it would be convenient to have special widget at home screen which will allow to write some text (without fancy org attributes - just plain text as we need to do it fast) and save it. It will write these notes to specified notebook (like 'default notebook' now). Maybe it will also be useful to display amount of entries in inbox so user will have motivation to clear it periodically.
What do you think? I will implement it anyway but having your blessing would be great : ]

**Comment by keithcrone** [comment]
How would this be different than the ability to click the persistent notification to add a note?

**Comment by fresheed** [comment]
Okay, I did not notice this option. Access to note adding screen via notification is more convenient than via widget. On the other hand, I would use simpler screen: just text area and Submit button. And amount of entries would be useful too.
So, notification approach seems more convenient. Thanks!

**Comment by nevenz** [comment]
There's also #62, widget with a new-note button. It might be better to open a small dialog instead of app, as you suggest, though I'm not sure that the benefit (if any) is worth it. More faster way to save the note in the note view might be more useful (perhaps a FAB in the bottom right corner).

In any case, feel free to open separate issues for either that, or note count per notebook which you mentioned. Thanks!
