### ISSUE TITLE
Subtree refiling commands are a bit far from reach

### ISSUE THREAD

**Issue by fedde-s** [orgzly/orgzly-android#113]
I think this app does a wonderful job of mapping important note-organising operations of Org-mode to the extremely different user interface values of an Android app / a portable-sized touch screen device, but I have found that (in addition to issues I already found reported elsewhere on this tracker) the cut and paste commands to move/refile notes and their children to a specific new location are slightly harder to access than I had intuited.

I believe that issue #14 could be one specific suggestion to improve this. Another one I thought of is this: would it make sense to somehow make long-pressing of the delete and insert options in the left-swipe submenu perform these actions?

**Comment by nevenz** [comment]
Instead of long-clicking the buttons for different actions (which might be hard to figure out that it's even possible - even the existence of swipe menu itself is not obvious), it might be better to make the swipe menus configurable, so you can pick the actions you want to put in them. There could be even more then 4-5 buttons in there and the menu could be horizontally scrollable (I'm not sure about UX if that's done, but it's an option).

So for:

* Left swipe note in notebook
* Right swipe note in notebook
* Left swipe note in search results
* Right swipe note in search results

you'd get to multi-select and rearrange the order of bunch of actions (cut, paste below, new under, mark as done, delete, ...).

Would that help?

There's definitely a lot of actions we want easily accessible and not enough space, which is a problem in general.

**Comment by fedde-s** [comment]
I see, long-pressing a button/icon other than to move it around is not something that I can recall occurring in any other Android UI, so I do agree that my suggestion would be a bad idea. I have some initial doubts about adding too much configuration too though.

At this moment I'm slightly more in favour of the suggestion in the other issue I referred to: having a paste button in the top bar while a single node is selected as a potential pasting location, instead of nested two menus deep.

**Comment by fedde-s** [comment]
Thanks for actually thinking of a fix! I didn't expect much to happen without digging into the code myself.
