### ISSUE TITLE
Can't quickly change TODO state

### ISSUE THREAD

**Issue by Chobbes** [orgzly/orgzly-android#208]
Currently changing a TODO item either involves tapping at least 4 times through vastly different locations on the screen, or the (not super obvious) swiping right on the task and either selecting the "Done" checkmark, or manually cycling with the two state cycling buttons.

Is it possible to do some / all of the following:

- make the TODO keyword itself a dropdown for different states
- make the right swipe have a dropdown option
- make tap and hold have a quick option for changing the state at the top

Currently I find it fairly arduous to change the state of an item, which I don't think is ideal for a "TODO list" app?

I think this is similar to being able to check checkboxes, which I believe is being added in version 1.6. It's just one of the most common things I would want to do in the app, so I want to be able to do it quickly!

Thanks!

**Comment by nevenz** [comment]
I'd vote for removing two cycling buttons and adding State button instead. It would open a dialog with available states to select. That would be swipe & 2 clicks.

**Comment by japhir** [comment]
>     What if right swipe cycles all the states
> 
> I think I would be fine with that personally, as I'm using only 3 states, but users might have a lot. Marking note as done, or setting a specific state would still be a pain (what #208 is about).

from #275: I would not like this at all, since my todo states involve GTD-states such as WAITING and SOMEDAY. And even an extra CANCELLED state as a second DONE state. Cycling would thus be very annoying. 

I think the above suggestion of a state button would work, but I'd still like to have a simple ✓ or swipe right to be able to mark something as the first DONE state quickly. What if we could just tap the TODO state text (small box, the rest of the item opens the todo item) and a selection thingy would pop-up?

**Comment by nevenz** [comment]
> I think the above suggestion of a state button would work, but I'd still like to have a simple ✓ or swipe right to be able to mark something as the first DONE state quickly.

Yes, that action would remain.

> What if we could just tap the TODO state text (small box, the rest of the item opens the todo item) and a selection thingy would pop-up?

I'm afraid it might be hard to click, being too small. And what about notes (no state) - something would have to be added for consistency (NOTE text or an icon).
