### ISSUE TITLE
Do not include past events in agenda view

### ISSUE THREAD

**Issue by kdudkov** [orgzly/orgzly-android#219]
Agenda view is great, but I see all past events (not todos, just scheduled events).
IMHO you should threat events in filters as TODO if scheduled date >= now and as DONE if its not.

**Comment by nevenz** [comment]
I think an option might be better to be able to control this.

Current behaviour might make sense for what "Scheduled time" means in Org mode, but I agree it's not ideal. Not without support for plain timestamps (reminders) at least.

**Comment by chrfreitag** [comment]
Why not turn the Agenda option on the drawer into a switch? Then whenever I select a search it would either appear in Agenda view or not in Agenda view depending on the state of the switch. This would make the Agenda view just as flexible as the searches themselves because it is just put on top of the searches as a different way of presentation.

**Comment by chrfreitag** [comment]
For me this would solve part of the problem because I see all my journal entries, which are notes with a scheduled time stamp for the time when I recorded them, appearing in the today's section of the agenda view. But I realize that my suggestion doesn't quite apply to the the whole idea of this issue.

**Comment by nevenz** [comment]
See [this comment](https://github.com/orgzly/orgzly-android/issues/203#issuecomment-341398333).

I'm rewriting the way search queries are parsed and generated and was thinking about  including another type of operator (besides those for conditions and sorting) - instructions (or options). So you could control the look of agenda, times expanding etc. using search queries.

I don't know if that makes sense?

Perhaps something similar to what you suggest could be implemented too later, as a way to reuse conditions and sorting of a saved search.

**Comment by chrfreitag** [comment]
The new agenda operators are actually the best and most flexible solution. I can only speak for my usage of orgzly: I went through my searches and saw that it is obvious for each search if it should be displayed in agenda view or just in a list of items. That's why it would make sense for me to include agenda operators in the search definitions.

**Comment by nevenz** [comment]
This will be possible in the next version by using query like:

`.it.done (s.ge.today or d.ge.today) ad.7`

"ad" standing for "agenda days".

Agenda has been removed from the drawer. Any query can include "ad.days" now.

**Comment by chrfreitag** [comment]
Thank you. This is wonderful.

**Comment by brandonbl79** [comment]
I know this is dated but curious about displaying past agenda items.  I can't see how to view ad. That occur in the past?  Any suggestions?

**Comment by nevenz** [comment]
> I know this is dated but curious about displaying past agenda items. I can't see how to view ad. That occur in the past? Any suggestions?

You can't yet, it's #587.
