### ISSUE TITLE
Dropbox sync not working

### ISSUE THREAD

**Issue by Emilv2** [orgzly/orgzly-android#22]
I linked Ozgzly to my dropbox account (I can see in my Dropbox settings that is is linked), but when I try to sync I get the message "Sync Not linked to Dropbox".

I am using the latest version 1.4.11 from the Google Play Store on MIUI.

**Comment by nevenz** [comment]
What about the button in Orgzly's `Settings ->  Respositories -> <YOUR-REPO>` ?

Is the icon blue and button says "unlink from dropbox"?

**Comment by Emilv2** [comment]
No, it says 'Link to dropbox'.   I follow all the steps, but it still says that:

![295533563](https://cloud.githubusercontent.com/assets/15071778/23349978/2740ef26-fcf2-11e6-94a8-b8105ca1257a.jpg)
![1839812765](https://cloud.githubusercontent.com/assets/15071778/23349977/273ab5f2-fcf2-11e6-8be4-46d64be57ea4.jpg)
![1486291513](https://cloud.githubusercontent.com/assets/15071778/23349976/2734536a-fcf2-11e6-9446-f197d35c89ae.jpg)
![1095697941](https://cloud.githubusercontent.com/assets/15071778/23349975/27222618-fcf2-11e6-8ba4-ad1e2a445725.jpg)

**Comment by nevenz** [comment]
Yeah, that doesn't look right. It's hard to test and try to reproduce though. There's been one same report some time ago. There was no conclusion.

Where are you connecting from and does accessing Dropbox fully work?

**Comment by nevenz** [comment]
So it's same problem the previous reporter had. Good to know it works with the app installed.

I'll close the issue as there's nothing much we can do. It's going to be a good reference for future though. 😄

**Comment by sean-sh** [comment]
I had the exact same issue and installing dropbox and signing in fixed the problem. So did using chrome as the default browser instead of firefox. When dropbox is installed, clicking on "link to dropbox" opens the dropbox app to ask for permission instead of the default browser and that's why it works. For some reason when it opens in firefox (at least Nightly) after clicking "Allow" and returning to orgzly, it doesn't detect that permission has been granted.

ps: thank you very much for creating Orgzly. This is awesome and I can now stop using Google notes for good.
