### ISSUE TITLE
Quitting issue from notebook shortcut

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#271]
While accessing a note from notebook shortcut, it would fall back into the notebooks list view after quitting, This maybe not need, I think most of users like to back arrives desktop directly, right?

**Comment by nevenz** [comment]
This was brought up before, for example [for widget](https://github.com/orgzly/orgzly-android/issues/62#issuecomment-300692310) and few more times I think. I did feel the same as you.

But I believe the current behaviour is [recommended](https://developer.android.com/design/patterns/navigation.html#into-your-app).

There's always a Home button on the device too. 😄

**Comment by NiceFeather** [comment]
Thanks for responding this, I got the guide of related design session for Android develpers, and also found BBC News app is the same with Gmail, etc. Actually I think there is little strange still about this official methodology recommended, maybe it comes from that those Home screen widget is an essentially list, but yours is a shortcut, I think a shortcut should be the simplest way of quickly accessing anything like specified notebook. My opinion is for your reference.

**Comment by nevenz** [comment]
It might apply to external links in general. There's the whole Home VS Up button argument too, latter not being used that much in apps any more (most having navigation drawer).

And different behaviour would also be strange in regard to that drawer, since it's there and notebook you opened is selected in it. Leaving the app from that spot is like ignoring it in a way. Notebook shortcut would have to open a notebook alone, in a separate activity. But then we'll have users wanted to do more once they're in the app.

So I have no idea, it's more of a preference, but not the kind to go to Settings.

In any case, you can always get back to where you were by pressing the Home button. On my device/launcher it brings me back to the same screen shortcut is on.
