### ISSUE TITLE
Add support for ownCloud

### ISSUE THREAD

**Issue by timo-a** [orgzly/orgzly-android#28]
I've tried so synchronize via internal storage, but to no avail.

**Comment by nevenz** [comment]
I'd be interested in hearing about the issue BTW, if it's something that can be fixed (you can open a new issue if so).

**Comment by timo-a** [comment]
There is a way to do it. 
`Import Org file`, local storage, `owncloud/user@server/file.org`.
At the time I have to then set link and force load. See #31 for that

**Comment by nevenz** [comment]
I think we'll still want support for direct sync with owdCloud, though a separate issue can be open for that (for more generic WebDAV sync).

**Comment by AngelBCN** [comment]
More and more applications work on nextcloud. Would it be possible now to be wallabag as an application within nextcloud?

**Comment by seth100** [comment]
+1

**Comment by Ekleog** [comment]
The solution of using `Import Org file` appears not to work for setting up a repository that can be synced with, for some reason.

**Comment by Ekleog** [comment]
@nevenz Yes, the issue is that (for Nextcloud at least) there is no way to select the Nextcloud folder in the menu for creating a repository, while it is possible in the `Import Org file` menu. I don't really understand why… maybe because the Nextcloud file is not local to the phone, but instead in a “Nextcloud” menu on the menu on the left of the file picker? and this menu doesn't appear in the repository addition tool (the Nextcloud app doesn't support syncing with files in a local directory currently)

**Comment by Ekleog** [comment]
Yes, #33 / #38 appear like the best options long-term, but…

For your workaround, I just tried adding
```
content://com.android.externalstorage.documents/tree/primary%3AAndroid/media/com.nextcloud.client/nextcloud/USER@SERVER/todo
```
and the same thing by replacing `@` with `%40`, as the preconfigured repository was
```
content://com.android.externalstorage.documents/tree/primary%3AOrgzly
```
However, it looks like it's not finding any file, despite the fact that when I go in the file manager, along the `Orgzly` directory used by default there *is* a file named
```
Android/media/com.nextcloud.client/nextcloud/USER@SERVER/todo/todo.org
```

Maybe this is due to recent versions of android forbidding access to other applications' files? I also tried manually turning on the `Storage` permission without more success.

Do you have an any of any other workaround? currently the best I'm thinking of is installing SyncThing in addition to Nextcloud to handle synchronization to my phone, but… :(

**Comment by nevenz** [comment]
You shouldn't need to modify URL manually if you select directory from the browser.

I've just tried it using a demo account I've found (hostname replaced with fake one below).

Account is:

```
demo@nextcloud.orgzly.com
```

Directory created is:

```
/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/demo@nextcloud.orgzly.com/
```

When selected as a repo from Orgzly, it's:

```
content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fmedia%2Fcom.nextcloud.client%2Fnextcloud%2Fdemo%40nextcloud.orgzly.com
```

Syncing appears to work (I get "Getting Started" saved in the directory and one manually created org file loaded).

**Comment by Ekleog** [comment]
Oh. Now I feel stupid, I hadn't noticed I actually had access to the `Android` folder from the browser…

Thank you! It appears to work now :D
And sorry for having wasted your time.
