### ISSUE TITLE
More frequent widget refresh

### ISSUE THREAD

**Issue by iexos** [orgzly/orgzly-android#293]
Hi,

I am using the widget to display tasks that are scheduled for `s.now`. I know this is a trade-off, but a bit more frequent refresh, like every 10min, would be useful for time-of-day specific tasks.

Looking at the source code it seems to me it should be refreshing every hour. But on my phone it did not refresh for more than two hours, unless I select the filter again from the drop down menu.

**Comment by NiceFeather** [comment]
There will transfer message to refresh all of widgets right now once any notes is modified, I found most of schedule apps can do it.

**Comment by nevenz** [comment]
> There will transfer message to refresh all of widgets right now once any notes is modified, I found most of schedule apps can do it.

This is already being done.

The issue here is that for the queries using relative time, period which widget displays is constantly shifting. Note scheduled 2 minutes from now won't appear in search results for "s.now" ("s.le.now"), but it should in 2 minutes.

BTW, this is not widget-specific, search results in app are also affected. Though it might be passable there, if we look at search results as the state of things at the time of the search.
