### ISSUE TITLE
Synchronization with internal storage not intuitive

### ISSUE THREAD

**Issue by timo-a** [orgzly/orgzly-android#31]
I assume after importing from local storage you have to set the link and `force load`/`force load` first.  

Below is what I tried:
Create a new file `untitled.org` in `/storage/emulated/0/DCIM/test`
Add `/storage/emulated/0/DCIM/test` as repository.
Import  `untitled.org`.
Add a note `foo`.
there is no option to save. //I would expect it while editing, not in main menu
(if you click on the magnification glass, `b.untitled` is in the query field -> confusion)
select sync.
the file has not changed.
Back in orgzly main menu there are 2 timestamps on `untitled`: first one from when the file was imported, second one from when we tried to sync. Next to it it says in red "Notebook has no link and one or more remote notebooks with the same name exist."
Longpress on the note, select `set Link`. So far there is `No Link`, select your repository.
Sync again, second timestamp is updated to current time, error message to "Link and remote notebook exist but notebook hasn't been synced before"
confusion :-) 
try main menu, longpress, `force save`
It works!
Add more notes and sync works!
Manipulate file externally and sync works!

**Comment by nevenz** [comment]
> I assume after importing from local storage you have to set the link and force load/force load first.

No, you generally don't want to import the notebook (using `Import Org file`), as that doesn't setup a link to repository. You want to just setup the repo and then use `Sync`.

> Import untitled.org.
> Add a note foo.
> there is no option to save. //I would expect it while editing, not in main menu

Save a note or notebook? There's ✔️ when you're editing the note, which saves it. And notebooks are saved when you `Sync` or do `Force Save`.

> (if you click on the magnification glass, b.untitled is in the query field -> confusion)

This is the default search query when you're inside the notebook. It means "search notes that are in 'untitled' notebook". See http://www.orgzly.com/help#Search

> "Link and remote notebook exist but notebook hasn't been synced before"

Yeah, that's confusing. What it means is that you have `untitled.org` in both repository and Orgzly, but not as a result of running `Sync` (since you used `Import Org file`). So Orgzly doesn't know what to do - which notebook to overwrite. Force saving, as you did, resolves this.

**Comment by timo-a** [comment]
I see, adding a repository and then syncing works perfectly!
