### ISSUE TITLE
"Created at" Settings option 

### ISSUE THREAD

**Issue by malcolm-mill** [orgzly/orgzly-android#332]
I use Orgzly 1.6.2 on Android. The 'Created at' setting (Settings->Notes and Notebooks->New Note->Created at) is good for logging things. I've just this moment upgraded to 1.6.6 and see this setting option is gone. The FireOS tablet version 1.6.5 is also "missing" the option. It's something I find useful and would like to see back. If not, no problem - still a brilliant App!

**Comment by nevenz** [comment]
This is moved to Settings / Sync.

It's done because created-at time is now always saved internally by Orgzly. And property is only used as a way to keep the time when syncing org files. Maybe is should be displayed in note view anyway. Though if "Use property for created-at time" is not enabled, it would get lost on next notebook load, so perhaps that would be confusing.

**Comment by nevenz** [comment]
Let me know if something is not working as you were expecting.

**Comment by malcolm-mill** [comment]
That's all working as expected, thanks.
