### ISSUE TITLE
Repeating dates in agenda search

### ISSUE THREAD

**Issue by gexplorer** [orgzly/orgzly-android#408]
When searching by scheduled date, it only gets next entry for items with repetition, while searching by agenda gives all the future entries in the date range.

I expect them to work the same way, that for me is the first one.

I'm submitting a **bug report** for version 1.6.9.

**Comment by nevenz** [comment]
This is intentional - query without `ad` is a simple search - it looks for a value of scheduled time, ignoring the repeater. And agenda (query which includes `ad`) displays a slice of time, taking repeaters into account.

You need agenda display, but with only the first entry in that period shown? A new query option could be added for that.

**Comment by gexplorer** [comment]
That's right, I'd like to see next items but without repetitive items,
because what I want to see in my agenda is what I have to do next and the
next repetition is not useful for me until the previous scheduled date is
not done.

**Comment by nevenz** [comment]
I think this is #330?

**Comment by gexplorer** [comment]
That it!

**Comment by nevenz** [comment]
> That it!

Great, thanks.
