### ISSUE TITLE
Mark as DONE repeated task twice per day

### ISSUE THREAD

**Issue by zervankoru** [orgzly/orgzly-android#414]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **feature request**.
Can you add possibility to mark as DONE repeated task more then one time?
For example I have a task:
Do something cool
Shelduted time: 01.01.2018 +1d

Today is 01.01.2018
I mark this task as DONE and shelduted time is now 02.01.2018
But I realize, that I can do this task for the next day also, but then I mark it again as DONE, it doesn't work. Status cannot to be changed to done twice per day.

**Comment by nevenz** [comment]
You want to mark is DONE again to move it to 03.01.2018?

Is your repeater really `+1d`? Or perhaps `.+1d` (which is default)?

**Comment by zervankoru** [comment]
.+1

**Comment by nevenz** [comment]
That would explain it because `.+` always adds period to *current* time.

- `.+1w` sets time to one week from now
- `+1w` adds one week to the (scheduled or deadline) time set
- `++1w` keeps adding one week to the time set until resulting time reaches future (e.g. from Monday in the past to first Monday in the future)

You can try using `++1d` for your task.

See https://orgmode.org/manual/Repeated-tasks.html for more info.

**Comment by zervankoru** [comment]
Thanks!
