### ISSUE TITLE
share to Orgzly, the shared content show be in Orgzly content instead of title

### ISSUE THREAD

**Issue by stardiviner** [orgzly/orgzly-android#471]
- [X] I have searched for existing issues that may be the same as or related to mine.

When I share a text to Orgzly, all the text is in Orgzly new notes title, I think in content would be better. WDYT?

**Comment by nevenz** [comment]
From which app are you sharing from? Or are you referring to selected text?

If app you are sharing from doesn't pass `EXTRA_SUBJECT` value, passed `EXTRA_TEXT` goes to the title. Otherwise `EXTRA_TEXT` will go to the content and `EXTRA_SUBJECT` to the title.

I think in most cases user will want some value in the title, as it's the fastest way to share something (because title cannot be empty).

I don't think there is a way to detect where the shared data is coming from, so if option is added to control the above, it would work the same for all sources which set only `EXTRA_TEXT`.

**Comment by stardiviner** [comment]
I see, thanks for explaination. I like this App. Thanks for your work.
