### ISSUE TITLE
Optional markdown

### ISSUE THREAD

**Issue by AeliusSaionji** [orgzly/orgzly-android#610]
New to orgmode and this app. Looking to evaluate if I can use this, a pretty glaring issue is the syntax. This is apparently unique to orgmode? I have never seen it before in my travels.

I'm not really interested in learning random syntax specifically for an android orgmode client. Optional markdown support would be appreciated.

Thanks

**Comment by matthsims** [comment]
orgmode is pretty explicitly designed with this syntax, the value of this app (to me, not to speak for others) is that it saves files in the orgmode format so it can be synced and used with orgmode elsewhere.

I would imagine there are better solutions to what you're looking for if you want markdown syntax.

**Comment by ScottFreeCode** [comment]
For what it's worth most of Orgzy's features would be non-standard extensions/conventions to Markdown, whereas they are all* compatible with the canonical Org Mode, which (as an Emacs library) has been available on every major OS since a year before Markdown was invented and half a decade before Android, GitHub or Stack Exchange came out. (The basic syntax is a decade or two older than that, and is… more or less equivalent to Markdown except that stars are headlines instead of hashes.)

Org format is also supported by GitHub, by plugins for most IDEs, and by several other apps like Orgzly. Quality of implementation varies and not all of these bother with the various task and calendar features, but it's widely available even if it isn't as popular as Markdown.

Having had the same reaction at first but being won over gradually by the feature set (and Emacs's programmability), I think a lot of the ugliness of Org format comes from usage rather than the syntax. If you try writing Markdown where most of your info is in either headlines or bullets and TODO keywords are added to those, that looks pretty ugly too. On the other hand if you use Org as markup for something other than a todo list, the way you would normally use Markdown with headlines breaking up sections of plain blocks of text, org files look mostly normal.

*Technically Orgzly uses its own search syntax instead of the Org Mode search syntax, but this isn't saved in the files.

**Comment by pepedelosbosques** [comment]
Perhaps it is easier to add toolbar like [this](https://aws1.discourse-cdn.com/standard14/uploads/cozic/original/2X/2/2488910ea24c7efe81c9d267e690f356a6520e14.gif)

It's hard to remember the syntax elements of all markup languages. Also, working with complex texts in mobile, it's tricky to move around and add the special characters (lots of taps and drags).

It would be great to integrate a toolbar to extend the editing ability when needed. It's more intuitive and easy to use. It is the same with the editor I'm using to craft this comment. I really don't care which markup language is. I just click in what i want and adapt to it. 

Do you know if there is some app or keyboard to integrate the toolbar directly on android ?

**Comment by AeliusSaionji** [comment]
That might be worth exploring in another issue. 

I'll close this one since I do not use this app. Markdown support would probably best be done as a fork anyway, since (as pointed out) this app lives in an existing orgmode ecosystem.
