### ISSUE TITLE
Local Syncing fails if SD card is formatted as internal memory

### ISSUE THREAD

**Issue by ibnishak** [orgzly/orgzly-android#614]
- [x] I have searched for existing issues that may be the same as or related to mine.

Android version: 6
Phone model: Lenovo A7010a48

As mentioned, I have an external SD-card formatted as internal memory, as allowed in android. Now instead of having a separate internal memory and external sd card, I have a single memory.

I reinstalled orgzly to be sure and did not change the default local repository location. It syncs as expected at first. Then randomly it stops recognizing the local repository and fails to sync with the error message `Failed creating ....`. 

`Sync > Repositories`correctly shows the repository location. Re-linking the repository works, but now it requires forced syncing of each file. However after sometime, it randomly stops syncing again.

**Comment by nevenz** [comment]
And you're using the Browser button to select it I assume, not entering it manually?

**Comment by nevenz** [comment]
One thing you can try is to use `file:/sdcard/Orgzly` (or whatever the path to that storage is) and see how that goes. Just to narrow the issue down.

**Comment by ibnishak** [comment]
@nevenz Yes, using browse to select it

**Comment by ibnishak** [comment]
![](https://i.imgur.com/7C50UAn.jpg)

**Comment by nevenz** [comment]
No, literally `file:/sdcard/Orgzly`.

**Comment by ibnishak** [comment]
So far it works. I will observe for 2-3 days and close the issue if sync still keeps up.

**Comment by ibnishak** [comment]
It is still syncing. Thank you for the help!! 

Great app you have there.

**Comment by nevenz** [comment]
BTW, this is not a long-term solution. With Android 10 and it's scoped storage, it will be necessery to use Storage Access Framework to access files which are not in app's private directories. That means using `content:` URL instead of `file:`.

So you might want to try and debug what's doing on there. It sounds like permission is not kept for some reason. Perhaps it's specific to your device/system. I see something called "Permission control" mentioned for some Lenovo models. Maybe you can check that.

**Comment by ibnishak** [comment]
Ok. If I upgrade and face the issue, I will let you know.
