### ISSUE TITLE
[Bug] Failed webDAV connection on Android 4.2

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#635]
- [x] I have searched for existing issues that may be the same as or related to mine.

I have an old cell phone, the system is Android 4.2, Just did several webDAV tests, enter URL, Username and Password, click "Test Connection", the application is crashed after displaying a message "Connecting...".   

Note that the WebDAV server and another mobile phone connection work well, and the URL, Username and Password entered are correct.

**Comment by nevenz** [comment]
Have you been able to report the crash? If installed from Google Play.

If not, it's hard to debug without more info. "adb logcat" output would be most useful.

What does the URL look like?

**Comment by NiceFeather** [comment]
>Have you been able to report the crash? If installed from Google Play.

No, I never installed anything from Google Play.

> What does the URL look like?

The same as my previous bug report is the second repository on the screenshot, as following:
![SmartSelect_20191114-164407_Orgzly](https://user-images.githubusercontent.com/28109556/68842321-2710de00-0701-11ea-999e-8f4486daaeb4.jpg)

**Comment by atamulis** [comment]
I have the same problem with an Android 4.4 Samsung tablet; orgzly connects correctly from an Android 6.0 phone. The WebDav server is on a Raspberry Pi in my house.

**Comment by kmuw** [comment]
Same problem on LineageOS 11, Android 4.4.4 (kitkat). URL is like `webdav://foo123.bar.baz.com:23422` and works perfectly with the nextcloud client.

Logcat says it expects API level 21+ (android 5+).

> W/dalvikvm(28117): Exception Ljava/lang/IllegalStateException; thrown while initializing Ll/j0/h/e;
D/AndroidRuntime(28117): Shutting down VM
W/dalvikvm(28117): threadid=1: thread exiting with uncaught exception (group=0x416f5ce0)
E/AndroidRuntime(28117): FATAL EXCEPTION: main
E/AndroidRuntime(28117): Process: com.orgzly, PID: 28117
E/AndroidRuntime(28117): java.lang.ExceptionInInitializerError
E/AndroidRuntime(28117):        at l.a0.<init>(OkHttpClient.kt:32)
E/AndroidRuntime(28117):        at l.a0$a.a(OkHttpClient.kt:6)
E/AndroidRuntime(28117):        at h.f.a.b.b.<init>(OkHttpSardine.java:2)
E/AndroidRuntime(28117):        at com.orgzly.android.q.q.a(WebdavRepo.kt:2)
E/AndroidRuntime(28117):        at com.orgzly.android.q.q.<init>(WebdavRepo.kt:2)
E/AndroidRuntime(28117):        at com.orgzly.android.q.q$a.a(WebdavRepo.kt:8)
E/AndroidRuntime(28117):        at com.orgzly.android.q.h.a(RepoFactory.kt:10)
E/AndroidRuntime(28117):        at com.orgzly.android.m.a.a(DataRepository.kt:372)
E/AndroidRuntime(28117):        at com.orgzly.android.ui.repos.ReposActivity.a(ReposActivity.kt:4)
E/AndroidRuntime(28117):        at com.orgzly.android.ui.repos.ReposActivity.a(ReposActivity.kt:2)
E/AndroidRuntime(28117):        at com.orgzly.android.ui.repos.ReposActivity$d.a(ReposActivity.kt:2)
E/AndroidRuntime(28117):        at com.orgzly.android.ui.repos.ReposActivity$d.a(ReposActivity.kt:1)
E/AndroidRuntime(28117):        at com.orgzly.android.ui.t$a.a(SingleLiveEvent.java:2)
E/AndroidRuntime(28117):        at androidx.lifecycle.LiveData.b(LiveData.java:6)
E/AndroidRuntime(28117):        at androidx.lifecycle.LiveData.a(LiveData.java:8)
E/AndroidRuntime(28117):        at androidx.lifecycle.LiveData.b(LiveData.java:14)
E/AndroidRuntime(28117):        at androidx.lifecycle.q.b(MutableLiveData.java:1)
E/AndroidRuntime(28117):        at com.orgzly.android.ui.t.b(SingleLiveEvent.java:5)
E/AndroidRuntime(28117):        at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
E/AndroidRuntime(28117):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(28117):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28117):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(28117):        at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(28117):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(28117):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(28117):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(28117):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(28117):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(28117): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
E/AndroidRuntime(28117):        at l.j0.h.a$c.a(AndroidPlatform.kt:12)
E/AndroidRuntime(28117):        at l.j0.h.e$a.c(Platform.kt:1)
E/AndroidRuntime(28117):        at l.j0.h.e$a.a(Platform.kt:1)
E/AndroidRuntime(28117):        at l.j0.h.e.<clinit>(Platform.kt:1)
E/AndroidRuntime(28117):        ... 28 more
W/ActivityManager(14329):   Force finishing activity com.orgzly/.android.ui.repos.ReposActivity

**Comment by nevenz** [comment]
> Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19

Ah thanks.

So this is [true for OkHttp](https://developer.squareup.com/blog/okhttp-3-13-requires-android-5) since v3.13. And that library is used by sardine-android which we use for WebDAV.

I've tried downgrading OkHttp to 3.12.x, but then the issue becomes that most devices with Android below version 5.0 only support TLS 1.0, so connecting to servers will fail.

I don't think there's a clean solution for this.
