### ISSUE TITLE
Question: Manually installed notebooks show as "empty"

### ISSUE THREAD

**Issue by Subspecies** [orgzly/orgzly-android#638]
Any ideas on this? I downloaded my notebooks from Dropbox onto my PC, then transferred them to the new device (OnePlus phone). They show grayed out and Orgzly indicates that they are empty. The location I used is: Android\DATA\com.orgzly 

Thanks for any help!

**Comment by nevenz** [comment]
Are did you import them to Orgzly? Is it related to #637?

**Comment by Subspecies** [comment]
Hi, thanks, yes, I thought, since I'm a beginner, fumbling around, I'd try just moving the files manually into what appears to be the proper directory. I didn't see a way to import. The help file has no import instructions as far as I could find. Is that what I'm missing: how to import?

**Comment by nevenz** [comment]
Ah OK. So data is stored in app's internal database. But notebooks can be exported to or imported from a "repository" which you need to set up. That *could* be a directory on your device, but since you're using Dropbox, it can also be a directory on Dropbox.

See http://www.orgzly.com/help#515ac68.

That page is all documentation there is currently.

> There is an error message under the grayed out title for my notebook in red letters saying "Force-loading failed."

There should be a reason following that, like "Force-loading failed: *some explanation*".

**Comment by Subspecies** [comment]
Hi, there was no additional explanation, though, on opening the notebook it sayd "Notebook has no notes." UPDATE: I searched instructions for the word "link" and found the instructions to do a long click on the notebook title in the list of notebooks, and to select "force load", and this worked. The notebook is now showing its contents. 

NEXT: I'll need to learn how to sync with Dropbox so I won't need to do it this way (manual transfer and force load). I'll look at the instructions you provided. And I guess any discussion of that belongs in #637. Thanks again!
