### ISSUE TITLE
Recurring Events Appear Twice in Agenda View

### ISSUE THREAD

**Issue by ryanpeach** [orgzly/orgzly-android#650]
- [X] I have searched for existing issues that may be the same as or related to mine.

If I have a daily recurring todo, in agenda view, it duplicates if the task is overdue. Is this normal?

![Screenshot_20200102-153455_Orgzly](https://user-images.githubusercontent.com/14838729/71691484-842a2700-2d75-11ea-84e9-242f018c004c.jpg)

**Comment by ScottFreeCode** [comment]
I sometimes see the same task show up once for schedule or other reminder and again for deadline if those happen to be on the same day. It kinda makes sense if those are different times, although sometimes I think it would be more helpful to show it once with the deadline also listed just so I know instead of showing it the second time.

Not sure if that's what's happening here though. I'd expect the second "brush teeth" to show the deadline instead of the schedule again, but maybe mine does that because I have a plain event instead of a schedule. Also not sure whether in general it should be considered a bug or not – at some point maybe I should look at what Org Mode's agenda does for comparison.

**Comment by nevenz** [comment]
It does look like a bug. I thought it was because the task is overdue, but it seems it only happens when the time is included (it's gone when 09:00 is removed I think?).

**Comment by nevenz** [comment]
There's also an "Overdue" header now, to make those separate from notes actually scheduled/deadline today.
