### ISSUE TITLE
Three requests: ignore inactive timestamps, create dates without state, and display events by timestamp first

### ISSUE THREAD

**Issue by nhmacuk** [orgzly/orgzly-android#683]
These are several feauture requests, should I make separate issues out of them?
Could you add the option to: 
- ignore inactive timestamps so they won't show up in the agenda
- create dates without a state (so (unscheduled) events) and be able to set the date through the interface 
- be able to display events/todos/etc by their timestamp first and then other properties, like in standard org-agenda-view (and not by agenda first and then by the timestamp)

**Comment by ScottFreeCode** [comment]
I believe you can use the same timestamp formats as org mode (`<YYYY-MM-DD Dow hh:mm repeater>` with all but the first chunk optional, or same but `[ ]` instead of `< >` for inactive) in the note title or body text to get an event and Orgzly ignores the inactive ones; they'll be `e.` in searches/agenda instead of `s.` or `d.` I'm fairly sure I've set events to inactive by changing their brackets to get them off my searches without marking them as DONE since they're not tasks.

What you can't currently do is use the datetime picker outside the schedule and deadline fields or (at least I don't think) have an inactive deadline or schedule (as opposed to the above "events"). (I'm not sure what Orgzly does if you give it an org file with an inactive schedule or deadline. It stores the files as structured data rather than the literal original text, so it probably either doesn't understand them or converts them into active ones because those are all it knows.) I think I recall seeing work on both of these for the next version, but the author can confirm or deny that they're coming up.

There's a section in the manual on sorting. (The following may not be relevant here, but: I don't find _defining_ a search or agenda particularly intuitive: if you pick it from the list you can't edit it, and have to pick "Searches" to edit them and have it stick but can't preview while editing from there. My best workaround is to edit a temporary search from the notebook view, then copypaste it into the saved searches editor; ideally I'd be able to just save searches I'm editing, or edit a saved search I'm viewing and choose whether those edits are saved, and then the saved searches list need not differ in behavior from accessing them from the sidebar.)

**Comment by nhmacuk** [comment]
per paragraph:
1. Sorry I meant: it is a scheduled inactive timestamp which is still displayed in orgzly, which is not the case in (what I think is standardly configured) org-agenda-view.
2. Yes that is exactly what I want to be able to do, so I won't have to manually type the dates into the body. When looking through the issues I didn't see it mentioned specifically, and issues seemed to be more related to the behavior of entries with states.
3. I have made several attempts to get the desired behavior through the searching/filtering system, but sadly have been unable to get this exact behavior so far.

**Comment by ScottFreeCode** [comment]
I don't remember now whether I saw discussion of the date picker or saw work in the source when I skimmed it to see what changes are coming up, a while back. I'll try to come back to this if I run across it again.

For the last point, are you thinking of the order the entries appear relative to each other? Or the way the content of a single entry is displayed? I think the order of entries is controlled by o in the search, e.g. that if you only are concerned with SCHEDULED then `o.s o.b o.p` would move the schedule time ahead of the notebook grouping and priority (`o.s o.p o.b` would also put priority ahead of notebook). For display of the note's content the only option I know of is about how much content is displayed. (It would certainly be nice to get more customizability around that!)

**Comment by nevenz** [comment]
UI for events (plain timestamps) is #108.

Sorting by using time first in agenda might be #298?

> it is a scheduled inactive timestamp which is still displayed in orgzly, which is not the case in (what I think is standardly configured) org-agenda-view.

This looks like a bug, they should be inserted to DB as inactive times.

Although Org mode doesn't seem to care about those at all. They are ignored when using shortcuts -- new `SCHEDULED` is added next to the one with inactive time and `C-u C-c C-s` doesn't remove it. How do you even add them in Org mode?

> The following may not be relevant here, but: I don't find defining a search or agenda particularly intuitive: if you pick it from the list you can't edit it, and have to pick "Searches" to edit them and have it stick but can't preview while editing from there. My best workaround is to edit a temporary search from the notebook view, then copypaste it into the saved searches editor; ideally I'd be able to just save searches I'm editing, or edit a saved search I'm viewing and choose whether those edits are saved, and then the saved searches list need not differ in behavior from accessing them from the sidebar.

I have this in my to-do list, you can open a new issue if you'd like.

**Comment by nhmacuk** [comment]
Oh I changed the scheduled timestamps to inactive ones (since my planning changed, but I wanted to keep the entries) by changing the surrounding < to [ using a macro.
Ah, oops I must have missed #108 and #298.

**Comment by nevenz** [comment]
I'll close this one since it has multiple requests. Issues for two already exist, #705 has been opened in the meantime.
