### ISSUE TITLE
Notebook shortcuts are unavaiabled

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#693]
- [x] I have searched for existing issues that may be the same as or related to mine.

With the latest release, all previous desktop notebook shortcuts are unavaiabled, and also after recreating them.

**Comment by nevenz** [comment]
> With the latest release, all previous desktop notebook shortcuts are unavaiabled, and also after recreating them.

What happens when you create a shortcut and click on it?

**Comment by NiceFeather** [comment]
> > With the latest release, all previous desktop notebook shortcuts are unavaiabled, and also after recreating them.
> 
> What happens when you create a shortcut and click on it?

I have a Microsoft Launcher, There will popup a toast to prompt "App isn't installed" after clicking any shortcut created by Orgzly.

**Comment by nevenz** [comment]
Have you installed app in different ways perhaps? Maybe F-Droid vs Google Play vs APK.

There could be issues with shortcuts if it's installed on SD card too.

Can you try to reinstall the app?

**Comment by keithcrone** [comment]
It started with the latest version. Your APK doesn't work either, across multiple devices and launchers. It's always a permission problem.

**Comment by nevenz** [comment]
> It's always a permission problem.

Ah, thanks, I managed to reproduce it.

I've changed the main activity to the new `LauncherActivity`, which is calling the old `MainActivity` (with the plan to create and start `IntroActivity` in the future for first-time users). Anyway, `MainActivity` now needed to be exported, so that the launcher can start it for the widget.

I didn't catch that since it apparently works on some devices (and emulator for example).
