### ISSUE TITLE
Problem with webdav

### ISSUE THREAD

**Issue by jagjordi** [orgzly/orgzly-android#729]
- [x] I have searched for existing issues that may be the same as or related to mine.

When trying to setup a webdav repo it gives a invalid login. The same exact URL and credentials work fine both in the same phone using chrome and in a windows computer both in a browser and with a mapped network drive. I have also tried a generic webdav client app in the phone and it works fine. It seems to be a problem with the app since all other ways works. What would be the steps to debugg this?

**Comment by dwarfmaster** [comment]
Did you try accessing the files precisely from the other ways, or did you just try to connect ? Because I had a similar error due to the fact that the .org file in the directory had wrong permissions, the the webdav directory itself had the right permission, so I could list the files from anywhere, but orgzly failed when it tried to actually access the files.

**Comment by jagjordi** [comment]
I have tried accessing and writing on the file using other methods and it worked fine. So I am unsure if it is related to permissions

**Comment by dane-johnson** [comment]
I fixed this issue by switching to basic authentication (from digest).
