### ISSUE TITLE
how to checkbox???

### ISSUE THREAD

**Issue by restinpieces** [orgzly/orgzly-android#744]
- I have searched for existing issues that may be the same as or related to mine.

Sorry to "waste" an issue, but i've searched extensively and nothing came up. 

How do you start a checkbox list? Adding to the example one works, but no matter what i try i cant start a new one.  Thx for the help.

**Comment by a13ph** [comment]
- [ ] add a line starting with `- [ ] ` like this in note text - [ ] after pressing return you’ll keep adding such checkbox items to the list- [ ] other list item symbols should work before brackets too, I thinkFrom: restinpiecesSent: Wednesday, July 29, 2020 11:37To: orgzly/orgzly-androidCc: SubscribedSubject: [orgzly/orgzly-android] how to checkbox??? (#744) I have searched for existing issues that may be the same as or related to mine.Sorry to "waste" an issue, but i've searched extensively and nothing came up.How do you start a checkbox list? Adding to the example one works, but no matter what i try i cant start a new one. Thx for the help.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by restinpieces** [comment]
Thank you, the trick was the right combination of space characters.  If I may make a suggestion: an easier pattern or a space tolerant pattern would be more userfriendly.

**Comment by nevenz** [comment]
> Thank you, the trick was the right combination of space characters. If I may make a suggestion: an easier pattern or a space tolerant pattern would be more user-friendly.

Org mode's format is used, see https://orgmode.org/manual/Checkboxes.html.

But UI is needed for this and planned (in a toolbar that will be added above keyboard).
