### ISSUE TITLE
hide keyboard when picking a date

### ISSUE THREAD

**Issue by LambdaAlpha** [orgzly/orgzly-android#776]
- I have searched for existing issues that may be the same as or related to mine.

- I request a feature that auto hide keyboard when picking a plan date or a due date.

**Comment by nevenz** [comment]
Do you see the keyboard *over* the timestamp dialog?

**Comment by LambdaAlpha** [comment]
> Do you see the keyboard *over* the timestamp dialog?

@nevenz yes, many times I click due date or schedule date just after edit task title, task content or task tag without hide keyboard by click back key manually. Then the time picker dialog just pops up over the keyboard. The keyboard covers the finish button (in a normal 16:9 screen with gboard). If I click back key now, the dialog will dismiss with the keyboard. So I have to retry again.

**Comment by nevenz** [comment]
I'm reluctant to apply #792 because it's useful to continue where you left off after adding a time. For example - you're writing a long text, then remember that you need to schedule the current note, you do that, leave the dialog and just continue writing.

But the keyboard covering any part of the dialog is weird and does need fixing. Though I'm confused with:

> Then the time picker dialog just pops up over the keyboard.

which is expected, and I don't see how it can cover dialog's buttons. Can you post a screenshot?

What device is this on?

**Comment by LambdaAlpha** [comment]
@nevenz 
![with keyboard](https://user-images.githubusercontent.com/20299598/102984695-ea8cf400-4548-11eb-8124-2d78a823a0fc.jpg)
![normal](https://user-images.githubusercontent.com/20299598/102984718-f24c9880-4548-11eb-80ca-11631b72467f.jpg)

**Comment by LambdaAlpha** [comment]
@nevenz I'm using xiaomi 6. When I say "over", I mean the dialog will pop up a little higher than where it will pop up without keyboard.

**Comment by nevenz** [comment]
> When I say "over", I mean the dialog will pop up a little higher than where it will pop up without keyboard.

I see. The keyboard always stays below the dialog for me. I don't know if something in the dialog is stealing the focus or whatever.

Anyway, I'll merge the PR, it's probably not worth debugging. If someone complains, we can consider reverting the change.
