### ISSUE TITLE
Add Sync button to search widget

### ISSUE THREAD

**Issue by MackieLoeffel** [orgzly/orgzly-android#85]
It would be nice to be able to sync from the search widget, at least as long #8 is not resolved. What do you think about adding a sync button to the header of the search widget, @nevenz ?

**Comment by nevenz** [comment]
I don't think it really fits in the widget. It can be confused with refreshing the widget itself, which we even mentioned implementing. Also, I'm not sure how much it makes things easier. You still need to hunt down the widget, which can be annoying if you're sharing to Orgzly from the browser for example.

How about adding a sync [action](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Actions) to the ongoing notification? Instead of being just for creating new notes, it can have two buttons - one for new note, one for sync.

That would make starting sync just *swipe down & click*, from anywhere, without interrupting your work.

**Comment by MackieLoeffel** [comment]
I like your idea. The notification is a better place than the widget.

**Comment by nevenz** [comment]
@ply, what about adding a sync shortcut to the home screen? You can long-click the main icon and then drag&drop the "Sync" to the home screen. This was done in #237. Does that work for you?

Swipe to sync from the app is now available in v1.8 too.

**Comment by ply** [comment]
@nevenz Thanks for pointing this out, it's good enough :) Anyway I think it'd be nice to have it inside the widget - when there is no space left on the home screen, or for having widget as big as possible.
