### ISSUE TITLE
Sync failed: "Notebook has no link and one of more remote notebooks with the same name exist"

### ISSUE THREAD

**Issue by AtomicNess123** [orgzly/orgzly-android#917]
Hi, I haven't found a fix to this issue.

I have a org file in my dropbox which I want to sync with my Android orgzly.
When I modify this org file on my Android or on my laptop, I get this message.
I have disabled and enabled autosync and always done the manual sync but nothing.
Any help welcome.

**Comment by IScoffedTheLaw** [comment]
I finally found a solution to this:

1. Backup your repo folder, just in case.
2. Delete all files inside of said folder.
3. Go to orgzly app, make sure you don't have any duplicate notebooks*
4. Sync

* This worked but I had a duplicate of a notebook with one capitalized and the other not capitalized after, which orgzly recognizes as the same file name for some reason and adds a (n) after the filename. Removing the notebook in the directory and orgzly fixed this.

I think this is what caused my initial problem because I try to use lowercase for anything I may sync with linux, and the notebook name is the filename. When I changed the name to lowercase orgzly created a new uncapitalized file with (n) after instead of syncing the filename change.

**Comment by AtomicNess123** [comment]
Thanks, it worked!

**Comment by artyhedgehog** [comment]
Another workaround worked for me: deleting a notebook from Orgzly, right after which it downloads from the cloud (not Dropbox, but a WebDav in my case). 

A bit tedious if you have lots of notebooks with the issue, but works if the version on the cloud is fresher.
